### PR TITLE
slight improvement to title slide animation

### PR DESCRIPTION
**Pull request by oliver-sanders**
Should fix the chrome "sudden transition" problem, does it do anything for the text colour?

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
Nice, this does seem to improve the transition on both Chrome & Firefox, but the text colour stays white for about 2 seconds after the transition ends such that the Met Office background has gone. So perhaps bump ``animation: titleout 3s;`` down to ``2s`` (a littel bit too late to go black is better than a little too early I would say as it could be seen as the final part of the transition)?

**Review by sadielbartholomew — COMMENTED** [review]
Nice, this does seem to improve the transition on both Chrome & Firefox, but the text colour stays white for about 2 seconds after the transition ends such that the Met Office background has gone. So perhaps bump ``animation: titleout 3s;`` down to ``2s`` (a littel bit too late to go black is better than a little too early I would say as it could be seen as the final part of the transition)?

**Comment by oliver-sanders** [comment]
Will try to work on the white/black text transition separately, that should change with the background.

**Comment by sadielbartholomew** [comment]
Ah fair enough, in that case this is good. Thanks.

**Review by sadielbartholomew — APPROVED** [review]

**Pull request merged**
